name: Py-checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        poetry-version: ['1.8.4', '2.1.3']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Cache Poetry environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install

      - name: Run ruff
        run: poetry run ruff check finam_trade_api

#      - name: Run mypy
#        run: poetry run mypy ./finam_trade_api

      - name: Run bandit
        run: |
          poetry run bandit -r finam_trade_api -x tests \
            --skip B101,B104,B311,B404,B603,B605

      - name: Check secrets
        run: |
          if [ -f .secrets.baseline ]; then
            poetry run detect-secrets scan --baseline .secrets.baseline
          else
            echo "::warning file=.secrets.baseline::Baseline файл отсутствует. Пропускаем проверку secrets"
          fi
